name: vision
dependencies:
- python=3.6.9
- pytorch=1.3.1
- torchvision=0.4.2
#- cudatoolkit=10.0
- numpy=1.17.4
- pandas=0.25.3
- pillow=6.2.1
- jupyter=1.0.0
- scipy=1.3.1
- scikit-learn=0.21.3
- scikit-image=0.15.0
- tqdm=4.39.0
- pip=19.3.1
- pyyaml=5.1.2
- gitpython=3.0.5
- requests=2.22.0
- pip:
    - flake8==3.7.9
    - tensorboardx==1.9
